# PyTorch

## PyTorchとは

- Pythonをベースとした科学計算フレームワーク
- PyTorchは以下に示す2つの機能を使用したいユーザを対象としている
    - Numpyベースの演算の代わりに、GPUを用いた高速な演算の実施
    - 高い柔軟性と実行速度を有したディープラーニング・プラットフォーム

## Tensors（テンソル）

- Numpy ndarrays のような多次元配列
- PyTorchにおいてテンソルはGPU上でも使用可能なため、処理速度を向上させることもできる

In [2]:
# PyTorch を import
import torch

# 空の3x5行列（テンソル）を生成
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# 乱数で初期化された3x5行列を生成
x = torch.rand(5, 3)
print(x)

tensor([[0.4439, 0.0658, 0.7821],
        [0.0810, 0.6266, 0.5267],
        [0.0605, 0.4213, 0.7444],
        [0.6444, 0.5903, 0.4697],
        [0.7043, 0.5086, 0.7340]])


In [4]:
# double型の数値0で初期化された5x3行列を生成
x = torch.zeros(5, 3, dtype=torch.double)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [5]:
# 直接値を指定して1x2行列を生成
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


### テンソルの操作（変形・変換等）

- テンソル同士の加算:
    - `x + y : return tensor`
    - `torch.add(x, y) : return tensor`, `torch.add(x, y, out=result)`
    - `y.add_(x) == (y += x)`
- インデクシング・スライシング:
    - `x[start:end, start:end, ...]`
- リサイズ:
    - `x.view(size1, size2, ...)`
- その他: https://pytorch.org/docs/stable/torch.html